### ISSUE TITLE
Combining VSCode Vim plugin with VSCode Easymotion

### ISSUE THREAD

**Issue by AlexString** [shadowndacorner/vscode-easymotion#3]
Greetings! I recently met this extension and I like the idea of it and appreciate the effort behind it.

I came up with an issue that would be nice if you could give it some of your time to see if there's any way to combine this two plugins as it would be the perfect efficiency combo. 

There's already someone who thought the same as me in this [opened issue](https://github.com/VSCodeVim/Vim/issues/7570) in VSCode plugin repo and that I already commented about the behavior between this two plugins.

I've checked your plugin code but I'm no familiar with VSCode plugin programming so I don't know if this issue has something to do with your plugin behavior or the vscode vim plugin behavior so I apologize if it's not this plugin 'responsability', even if that's the case I would like to know what do you think about it. thanks.

**Comment by shadowndacorner** [comment]
Hey, thanks!  Glad you like the extension!

So I think there may be a bit of confusion here due to the naming of this extension.  EasyMotion was originally a plugin for Vim.  VSCodeVim has an implementation of EasyMotion as it works in Vim, which you can enable with the setting `"vim.easymotion": true` as detailed in the VSCodeVim readme.  The issue that you linked seems to be referring to that.  If you're already using VSCodeVim, I'd recommend trying that out rather than this extension as it is more in line with how Vim works.  I actually wrote this extension to mimic that plugin in a way that made sense to me, as I'm pretty bad at Vim style text editing but really enjoyed being able to jump around like that.

Afaik it would not be possible to make this extension compatible with VSCodeVim without directly integrating this code into VSCodeVim as both take control of VS Code's `type` event.  I don't have any plans to do so, but if you really wanted to, you could fork VSCodeVim and try to do that integration yourself.  However, I really think the best option for you would be to try out the EasyMotion plugin that is built into VSCodeVim.

**Comment by AlexString** [comment]
My bad!

I read your response and went directly to search for it on the [repo readme](https://github.com/VSCodeVim/Vim#vim-easymotion) thanks for made me know about it, I feel ignorant for not searching fully for it's 'native' implementation, quite new on this vim things too. Thanks!
